//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pamela_4._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        public Categoria()
        {
            this.HistoricoAnuals = new HashSet<HistoricoAnual>();
        }
    
        public int IDCategoria { get; set; }
        public string NombreCategoria { get; set; }
        public string DuracionPeriodo { get; set; }
        public int NumeroHoras { get; set; }
        public decimal Parcialidad1 { get; set; }
        public Nullable<decimal> Parcialidad2 { get; set; }
        public Nullable<decimal> Parcialidad3 { get; set; }
        public Nullable<decimal> Parcialidad4 { get; set; }
        public Nullable<decimal> Parcialidad5 { get; set; }
        public Nullable<System.DateTime> FechaP1 { get; set; }
        public Nullable<System.DateTime> FechaP2 { get; set; }
        public Nullable<System.DateTime> FechaP3 { get; set; }
        public Nullable<System.DateTime> FechaP4 { get; set; }
        public Nullable<System.DateTime> FechaP5 { get; set; }
    
        public virtual ICollection<HistoricoAnual> HistoricoAnuals { get; set; }
    }
}
