//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pamela_4._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FolioAnual
    {
        public int IDFolio { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime Fecha { get; set; }
        public string ModoPago { get; set; }
        public int IDHistorico { get; set; }
        public Nullable<int> Parcialidad { get; set; }
    
        public virtual HistoricoAnual HistoricoAnual { get; set; }
    }
}
