//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pamela_4._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tutor
    {
        public Tutor()
        {
            this.Becadoes = new HashSet<Becado>();
        }
    
        public int IDTutor { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Actividad { get; set; }
        public string TelCasa { get; set; }
        public string TelCelular { get; set; }
        public string TelTrabajo { get; set; }
        public string Domicilio { get; set; }
        public string CorreoElectronico { get; set; }
    
        public virtual ICollection<Becado> Becadoes { get; set; }
    }
}
